# Generated by Django 2.0.4 on 2018-07-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='processed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
