# Generated by Django 2.0.4 on 2018-04-23 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='date',
            field=models.DateField(),
        ),
    ]
