# Generated by Django 2.0.4 on 2018-04-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0002_auto_20180423_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ['-date'], 'verbose_name': 'Version', 'verbose_name_plural': 'Version'},
        ),
        migrations.AddField(
            model_name='version',
            name='critical',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
