# Generated by Django 2.0.4 on 2018-07-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0002_userdata_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
