# Generated by Django 2.0.4 on 2018-04-14 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0002_auto_20180331_0341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdata',
            options={'ordering': ['-score']},
        ),
    ]
