# Generated by Django 2.0.4 on 2018-07-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0003_auto_20180723_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='processed',
            field=models.BooleanField(),
        ),
    ]
