# Generated by Django 2.0.4 on 2018-04-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0003_auto_20180414_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True)),
                ('log', models.TextField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Version',
                'verbose_name_plural': 'Version',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='userdata',
            options={'ordering': ['-score'], 'verbose_name_plural': 'User Data'},
        ),
    ]
