# Generated by Django 2.0.4 on 2018-07-23 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0004_auto_20180723_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Data.Version'),
        ),
    ]
