# Generated by Django 2.0.4 on 2018-04-19 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0004_auto_20180419_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ['date'], 'verbose_name': 'Version', 'verbose_name_plural': 'Version'},
        ),
    ]
