# Generated by Django 2.0.4 on 2018-06-11 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0004_auto_20180611_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
