# Generated by Django 2.0.4 on 2018-06-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0005_auto_20180611_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='log',
            field=models.TextField(max_length=500),
        ),
    ]
