# Generated by Django 2.0.4 on 2018-06-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='version',
            field=models.FloatField(),
        ),
    ]
