# Generated by Django 2.0.4 on 2018-06-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180622_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='version',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
