# Generated by Django 2.0.4 on 2018-06-23 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180623_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='done',
            new_name='read',
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(max_length=1000),
        ),
    ]
