# Generated by Django 2.0.4 on 2018-06-23 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180623_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Data.Version'),
        ),
    ]
